export interface Flashcard {
  id: string;
  subject: string;
  topicSlug: string;
  cardType: 'flashcard_flip' | 'interactive_drill';
  frontPrompt: string;
  backAnswer: string;
  options?: { key: 'A' | 'B' | 'C' | 'D'; text: string; isCorrect: boolean }[];
  socraticHint: string;
  textbookRef: string;
  srsEaseFactor?: number;
}

export const INITIAL_DECKS: Record<string, Flashcard[]> = {
  use_of_english: [
    {
      id: 'eng-1',
      subject: 'use_of_english',
      topicSlug: 'concord-rules',
      cardType: 'interactive_drill',
      frontPrompt: 'Neither the principal nor the teachers _______ present at the PTA emergency meeting yesterday.',
      backAnswer: 'were',
      options: [
        { key: 'A', text: 'was', isCorrect: false },
        { key: 'B', text: 'were', isCorrect: true },
        { key: 'C', text: 'is', isCorrect: false },
        { key: 'D', text: 'are', isCorrect: false },
      ],
      socraticHint: 'When "neither...nor" connects two subjects of different numbers, the verb agrees with the closer subject. Look at "teachers" right before the blank.',
      textbookRef: 'A-Z of Use of English by Dele Ashade, Chapter 4: Proximity Concord',
    },
    {
      id: 'eng-2',
      subject: 'use_of_english',
      topicSlug: 'the-lekki-headmaster',
      cardType: 'flashcard_flip',
      frontPrompt: 'In Kabir Alabi Garba’s "The Lekki Headmaster", what central philosophy drove Mr. Benjamin\'s educational reform?',
      backAnswer: 'Holistic discipline combined with experiential vocational learning and moral accountability.',
      socraticHint: 'Think about Mr. Benjamin\'s resistance to rote learning and his introduction of practical community projects.',
      textbookRef: 'The Lekki Headmaster by Kabir Alabi Garba, Chapter 2: The Vision for Lekki Community High',
    },
    {
      id: 'eng-3',
      subject: 'use_of_english',
      topicSlug: 'lexis-and-structure',
      cardType: 'interactive_drill',
      frontPrompt: 'Choose the word closest in meaning to the underlined word: The minister gave an *equivocal* response during the press briefing.',
      backAnswer: 'Ambiguous',
      options: [
        { key: 'A', text: 'Decisive', isCorrect: false },
        { key: 'B', text: 'Ambiguous', isCorrect: true },
        { key: 'C', text: 'Hostile', isCorrect: false },
        { key: 'D', text: 'Enthusiastic', isCorrect: false },
      ],
      socraticHint: 'The root "equi-" (equal) and "voc-" (voice/call) suggests speaking with two voices so that the meaning is deliberately unclear.',
      textbookRef: 'A-Z of Use of English by Dele Ashade, Lexis: Latin & Greek Root Formations',
    },
    {
      id: 'eng-4',
      subject: 'use_of_english',
      topicSlug: 'the-lekki-headmaster',
      cardType: 'interactive_drill',
      frontPrompt: 'In "The Lekki Headmaster", which character represented the corrupt administrative interference against school improvements?',
      backAnswer: 'Chief Balogun',
      options: [
        { key: 'A', text: 'Chief Balogun', isCorrect: true },
        { key: 'B', text: 'Mrs. Adebisi', isCorrect: false },
        { key: 'C', text: 'Inspector Danladi', isCorrect: false },
        { key: 'D', text: 'Mr. Okafor', isCorrect: false },
      ],
      socraticHint: 'Recall the community leader who pressured the school board to award unverified contracts.',
      textbookRef: 'The Lekki Headmaster by Kabir Alabi Garba, Character Index: Antagonists',
    },
    {
      id: 'eng-5',
      subject: 'use_of_english',
      topicSlug: 'idiomatic-expressions',
      cardType: 'flashcard_flip',
      frontPrompt: 'What does the idiom "to take the bull by the horns" mean in JAMB Lexis questions?',
      backAnswer: 'To face a difficult or dangerous situation directly with courage and decisiveness.',
      socraticHint: 'Imagine grasping a charging bull directly by its horns rather than running away from it.',
      textbookRef: 'A-Z of Use of English by Dele Ashade, Section III: High-Yield Idioms',
    },
  ],

  mathematics: [
    {
      id: 'math-1',
      subject: 'mathematics',
      topicSlug: 'trigonometry',
      cardType: 'interactive_drill',
      frontPrompt: 'If sin θ = 3/5 and θ is acute, find the exact value of cos 2θ.',
      backAnswer: '7/25',
      options: [
        { key: 'A', text: '7/25', isCorrect: true },
        { key: 'B', text: '24/25', isCorrect: false },
        { key: 'C', text: '-7/25', isCorrect: false },
        { key: 'D', text: '16/25', isCorrect: false },
      ],
      socraticHint: 'Use the double-angle identity: cos 2θ = 1 - 2 sin²θ. Compute 1 - 2*(3/5)²',
      textbookRef: 'New General Mathematics for SS3, Chapter 8: Double Angle Formulae',
    },
    {
      id: 'math-2',
      subject: 'mathematics',
      topicSlug: 'trigonometry',
      cardType: 'flashcard_flip',
      frontPrompt: 'State the Pythagorean trigonometric identity relating secant and tangent.',
      backAnswer: '1 + tan² θ = sec² θ',
      socraticHint: 'Divide the fundamental identity sin² θ + cos² θ = 1 through by cos² θ.',
      textbookRef: 'New General Mathematics for SS2, Chapter 12: Trigonometric Identities',
    },
    {
      id: 'math-3',
      subject: 'mathematics',
      topicSlug: 'calculus-differentiation',
      cardType: 'interactive_drill',
      frontPrompt: 'Differentiate y = (3x² - 5)⁴ with respect to x.',
      backAnswer: '24x(3x² - 5)³',
      options: [
        { key: 'A', text: '12x(3x² - 5)³', isCorrect: false },
        { key: 'B', text: '24x(3x² - 5)³', isCorrect: true },
        { key: 'C', text: '4(3x² - 5)³', isCorrect: false },
        { key: 'D', text: '6x(3x² - 5)⁴', isCorrect: false },
      ],
      socraticHint: 'Apply the Chain Rule: dy/dx = n * [u(x)]^(n-1) * u\'(x). Here u(x) = 3x² - 5, so u\'(x) = 6x.',
      textbookRef: 'New General Mathematics for SS3, Calculus: Chain Rule',
    },
    {
      id: 'math-4',
      subject: 'mathematics',
      topicSlug: 'matrices-determinants',
      cardType: 'flashcard_flip',
      frontPrompt: 'For a 2x2 matrix A = [[a, b], [c, d]], what is det(A) and the condition for singular matrix?',
      backAnswer: 'det(A) = ad - bc. Matrix A is singular when det(A) = 0 (no inverse exists).',
      socraticHint: 'Calculate cross-diagonal subtraction (main diagonal minus secondary diagonal).',
      textbookRef: 'New General Mathematics for SS3, Matrices: Singular Matrix Inversion',
    },
    {
      id: 'math-5',
      subject: 'mathematics',
      topicSlug: 'coordinate-geometry',
      cardType: 'interactive_drill',
      frontPrompt: 'Find the gradient of the line perpendicular to 2x + 4y = 9.',
      backAnswer: '2',
      options: [
        { key: 'A', text: '-1/2', isCorrect: false },
        { key: 'B', text: '2', isCorrect: true },
        { key: 'C', text: '-2', isCorrect: false },
        { key: 'D', text: '1/2', isCorrect: false },
      ],
      socraticHint: 'Rearrange to y = mx + c: 4y = -2x + 9 => m₁ = -1/2. Perpendicular lines satisfy m₁ * m₂ = -1.',
      textbookRef: 'New General Mathematics for SS2, Coordinate Geometry: Perpendicular Slopes',
    },
  ],

  physics: [
    {
      id: 'phy-1',
      subject: 'physics',
      topicSlug: 'mechanics-projectiles',
      cardType: 'interactive_drill',
      frontPrompt: 'A projectile is launched with velocity u at angle θ to horizontal. What is its maximum horizontal range condition?',
      backAnswer: 'θ = 45°, where Range R_max = u² / g',
      options: [
        { key: 'A', text: 'θ = 30°, R = u² / 2g', isCorrect: false },
        { key: 'B', text: 'θ = 45°, R = u² / g', isCorrect: true },
        { key: 'C', text: 'θ = 60°, R = u² sin 60° / g', isCorrect: false },
        { key: 'D', text: 'θ = 90°, R = 0', isCorrect: false },
      ],
      socraticHint: 'The formula for range is R = (u² sin 2θ) / g. The maximum of sin 2θ occurs when 2θ = 90°.',
      textbookRef: 'New School Physics by M.W. Anyakoha, Chapter 3: Projectile Motion',
    },
    {
      id: 'phy-2',
      subject: 'physics',
      topicSlug: 'mechanics-circular-motion',
      cardType: 'flashcard_flip',
      frontPrompt: 'State the formula for centripetal force acting on an object of mass m moving with linear velocity v along radius r.',
      backAnswer: 'F = (m * v²) / r  or  F = m * ω² * r  (directed towards the centre of the circular path).',
      socraticHint: 'Remember Newton\'s second law F = ma, where centripetal acceleration a_c = v² / r.',
      textbookRef: 'New School Physics by M.W. Anyakoha, Chapter 4: Circular Motion and Gravitation',
    },
    {
      id: 'phy-3',
      subject: 'physics',
      topicSlug: 'waves-optics',
      cardType: 'interactive_drill',
      frontPrompt: 'Light travels from a medium of refractive index 1.5 into air (n=1.0). What is the critical angle c for total internal reflection?',
      backAnswer: '41.8°',
      options: [
        { key: 'A', text: '30.0°', isCorrect: false },
        { key: 'B', text: '41.8°', isCorrect: true },
        { key: 'C', text: '48.6°', isCorrect: false },
        { key: 'D', text: '60.0°', isCorrect: false },
      ],
      socraticHint: 'By Snell\'s law at critical angle: sin c = 1 / n = 1 / 1.5 = 0.6667. Compute arcsin(0.6667).',
      textbookRef: 'New School Physics by M.W. Anyakoha, Chapter 14: Refraction and Critical Angle',
    },
    {
      id: 'phy-4',
      subject: 'physics',
      topicSlug: 'electrostatics',
      cardType: 'flashcard_flip',
      frontPrompt: 'State Coulomb\'s Law of electrostatic force between two point charges q₁ and q₂ separated by distance r.',
      backAnswer: 'F = (1 / 4πε₀) * (|q₁ * q₂| / r²), where 1/4πε₀ ≈ 9.0 × 10⁹ N·m²/C².',
      socraticHint: 'Notice the inverse-square dependency on distance r, identical in form to Newton\'s law of gravitation.',
      textbookRef: 'New School Physics by M.W. Anyakoha, Chapter 18: Electrostatic Fields',
    },
    {
      id: 'phy-5',
      subject: 'physics',
      topicSlug: 'current-electricity',
      cardType: 'interactive_drill',
      frontPrompt: 'Two resistors of 6 Ω and 12 Ω are connected in parallel across a 24V battery of negligible internal resistance. What is the total current drawn?',
      backAnswer: '6 A',
      options: [
        { key: 'A', text: '2 A', isCorrect: false },
        { key: 'B', text: '4 A', isCorrect: false },
        { key: 'C', text: '6 A', isCorrect: true },
        { key: 'D', text: '8 A', isCorrect: false },
      ],
      socraticHint: 'Equivalent resistance R_eq = (6 * 12) / (6 + 12) = 72 / 18 = 4 Ω. Current I = V / R_eq = 24 / 4.',
      textbookRef: 'New School Physics by M.W. Anyakoha, Chapter 20: Electric Circuits & Ohm\'s Law',
    },
  ],

  biology: [
    {
      id: 'bio-1',
      subject: 'biology',
      topicSlug: 'genetics-heredity',
      cardType: 'interactive_drill',
      frontPrompt: 'In a monohybrid cross between two heterozygous tall pea plants (Tt), what proportion of offspring will be phenotypically tall?',
      backAnswer: '75% (3/4)',
      options: [
        { key: 'A', text: '25%', isCorrect: false },
        { key: 'B', text: '50%', isCorrect: false },
        { key: 'C', text: '75%', isCorrect: true },
        { key: 'D', text: '100%', isCorrect: false },
      ],
      socraticHint: 'Draw a Punnett square for Tt × Tt: genotypes are 1 TT : 2 Tt : 1 tt. Both TT and Tt express the dominant tall phenotype.',
      textbookRef: 'Modern Biology for Senior Secondary Schools by S.T. Ramalingam, Chapter 24: Mendelian Genetics',
    },
    {
      id: 'bio-2',
      subject: 'biology',
      topicSlug: 'cell-biology',
      cardType: 'flashcard_flip',
      frontPrompt: 'What is the primary function of ribosomes and the rough endoplasmic reticulum in eukaryotic cells?',
      backAnswer: 'Protein synthesis and polypeptide folding/transportation.',
      socraticHint: 'Ribosomes translate mRNA into amino acid sequences, while the ER provides membranous channels for their modification.',
      textbookRef: 'Modern Biology by S.T. Ramalingam, Chapter 3: Cellular Ultrastructure',
    },
    {
      id: 'bio-3',
      subject: 'biology',
      topicSlug: 'plant-nutrition',
      cardType: 'interactive_drill',
      frontPrompt: 'Which of the following mineral elements is an essential component of the chlorophyll molecule in plants?',
      backAnswer: 'Magnesium',
      options: [
        { key: 'A', text: 'Iron', isCorrect: false },
        { key: 'B', text: 'Magnesium', isCorrect: true },
        { key: 'C', text: 'Calcium', isCorrect: false },
        { key: 'D', text: 'Phosphorus', isCorrect: false },
      ],
      socraticHint: 'Magnesium occupies the central porphyrin ring of chlorophyll; its deficiency causes chlorosis (yellowing between leaf veins).',
      textbookRef: 'Modern Biology by S.T. Ramalingam, Chapter 8: Autotrophic Nutrition in Plants',
    },
    {
      id: 'bio-4',
      subject: 'biology',
      topicSlug: 'circulatory-system',
      cardType: 'flashcard_flip',
      frontPrompt: 'Why does the left ventricle of the human mammalian heart have a significantly thicker muscular wall than the right ventricle?',
      backAnswer: 'The left ventricle pumps oxygenated blood against high systemic vascular resistance throughout the entire body, whereas the right ventricle only pumps to the adjacent lungs (pulmonary circuit).',
      socraticHint: 'Compare the distance and pressure required to reach body extremities versus nearby pulmonary capillaries.',
      textbookRef: 'Modern Biology by S.T. Ramalingam, Chapter 14: Transport Systems in Mammals',
    },
    {
      id: 'bio-5',
      subject: 'biology',
      topicSlug: 'ecology',
      cardType: 'interactive_drill',
      frontPrompt: 'In ecological succession, the first group of pioneer organisms to colonize bare rock are typically:',
      backAnswer: 'Lichens and mosses',
      options: [
        { key: 'A', text: 'Annual herbs', isCorrect: false },
        { key: 'B', text: 'Lichens and mosses', isCorrect: true },
        { key: 'C', text: 'Shrubs', isCorrect: false },
        { key: 'D', text: 'Hardwood trees', isCorrect: false },
      ],
      socraticHint: 'Pioneers must secrete mild acids to weather rock into primitive soil particles without pre-existing organic matter.',
      textbookRef: 'Modern Biology by S.T. Ramalingam, Chapter 31: Primary Ecological Succession',
    },
  ],
};
