import { boolean, decimal, jsonb, integer, pgEnum, pgTable, real, text, timestamp, uuid, varchar } from 'drizzle-orm/pg-core';

export const subjectEnum = pgEnum('subject_enum', [
  'USE_OF_ENGLISH',
  'MATHEMATICS',
  'PHYSICS',
  'CHEMISTRY',
  'BIOLOGY',
  'ECONOMICS',
  'GOVERNMENT',
]);

export type SubjectEnumType = (typeof subjectEnum.enumValues)[number];

export const users = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  email: varchar('email', { length: 255 }).notNull().unique(),
  name: text('name'),
  fullName: varchar('full_name', { length: 255 }),
  targetCourse: text('target_course'), // e.g., 'Medicine', 'Law', 'Engineering'
  targetScore: integer('target_score').default(250).notNull(),
  targetJambScore: integer('target_jamb_score').default(250),
  streakCount: integer('streak_count').default(0).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const flashcards = pgTable('flashcards', {
  id: uuid('id').primaryKey().defaultRandom(),
  subject: varchar('subject', { length: 100 }).notNull(), // e.g. 'use_of_english'
  topicSlug: varchar('topic_slug', { length: 100 }).notNull(),
  cardType: varchar('card_type', { length: 50 }).notNull(), // 'flashcard_flip' | 'interactive_drill'
  frontPrompt: text('front_prompt').notNull(),
  backAnswer: text('back_answer').notNull(),
  options: jsonb('options'), // [{ key: 'A', text: '...', isCorrect: true }]
  socraticHint: text('socratic_hint').notNull(),
  textbookRef: text('textbook_ref').notNull(),
  srsEaseFactor: integer('srs_ease_factor').default(250).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const prescribedNovels = pgTable('prescribed_novels', {
  id: uuid('id').primaryKey().defaultRandom(),
  examYear: integer('exam_year').notNull().unique(),
  bookTitle: varchar('book_title', { length: 255 }).notNull(),
  author: varchar('author', { length: 255 }).notNull(),
  summary: text('summary'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const trackCategoryEnum = pgEnum('track_category_enum', [
  'JAMB_UTME',
  'PROGRAMMING',
  'HOW_TECH_WORKS',
  'DATA_ANALYTICS',
  'ARTIFICIAL_INTELLIGENCE',
  'CRYPTO_WEB3',
  'QUANTUM_COMPUTING',
]);

export const cardTypeEnum = pgEnum('card_type_enum', [
  'VISUAL_INTUITION',
  'SOCRATIC_PROBE',
  'TACTILE_CHECK',
  'CONCEPT_WIDGET',
  'MASTERY_CHECK',
]);

export const courses = pgTable('courses', {
  id: uuid('id').primaryKey().defaultRandom(),
  category: trackCategoryEnum('category').notNull(),
  subject: varchar('subject', { length: 50 }).default('GENERAL').notNull(),
  title: varchar('title', { length: 255 }).notNull(),
  description: text('description').notNull(),
  iconName: varchar('icon_name', { length: 50 }).notNull(),
});

export const modules = pgTable('modules', {
  id: uuid('id').primaryKey().defaultRandom(),
  courseId: uuid('course_id').references(() => courses.id).notNull(),
  title: varchar('title', { length: 255 }).notNull(),
  nodeOrder: integer('node_order').notNull(),
  examYear: integer('exam_year'),
  historicalWeight: real('historical_weight').default(0).notNull(),
  isHighYield: boolean('is_high_yield').default(false).notNull(),
});

export const cards = pgTable('cards', {
  id: uuid('id').primaryKey().defaultRandom(),
  moduleId: uuid('module_id').references(() => modules.id).notNull(),
  cardType: cardTypeEnum('card_type').notNull(),
  stepOrder: integer('step_order').notNull(),
  questionText: text('question_text').notNull(),
  contentPayload: jsonb('content_payload').notNull(),
});

export const syllabusTopics = pgTable('syllabus_topics', {
  id: uuid('id').primaryKey().defaultRandom(),
  subject: subjectEnum('subject').notNull(),
  topicName: varchar('topic_name', { length: 255 }).notNull(),
  subTopicName: varchar('sub_topic_name', { length: 255 }).notNull(),
  objectives: text('objectives').notNull(),
  questionWeight: varchar('question_weight', { length: 50 }),
  orderIndex: integer('order_index').default(0).notNull(),
  examYear: integer('exam_year').default(2026).notNull(),
  prescribedNovelId: uuid('prescribed_novel_id').references(() => prescribedNovels.id),
});

export const explanationSourceEnum = pgEnum('explanation_source_enum', [
  'aloc',           // from ALOC API solution field (cleaned)
  'ai_generated',   // generated by Gemini — needs review before launch
  'human_reviewed', // approved by a subject teacher
  'placeholder',    // no real explanation yet
]);

export const pastQuestions = pgTable('past_questions', {
  id: uuid('id').primaryKey().defaultRandom(),
  alocId: integer('aloc_id').unique(),
  subject: subjectEnum('subject'),
  subjectSlug: varchar('subject_slug', { length: 50 }),
  topicId: uuid('topic_id').references(() => syllabusTopics.id).notNull(),
  examType: varchar('exam_type', { length: 20 }).default('UTME').notNull(),
  year: varchar('year', { length: 20 }).notNull(),
  questionText: text('question_text').notNull(),
  options: jsonb('options').notNull(),
  correctOption: varchar('correct_option', { length: 10 }).notNull(),
  explanation: text('explanation').notNull(),
  explanationSource: explanationSourceEnum('explanation_source').default('placeholder').notNull(),
  explanationReviewed: boolean('explanation_reviewed').default(false).notNull(),
  examYear: integer('exam_year').default(2026).notNull(),
  prescribedNovelId: uuid('prescribed_novel_id').references(() => prescribedNovels.id),
});

export const examAttempts = pgTable('exam_attempts', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').references(() => users.id).notNull(),
  score: integer('score').notNull(),
  totalScore: integer('total_score').default(0).notNull(),
  englishScore: integer('english_score').default(0).notNull(),
  subject2Score: integer('subject_2_score').default(0).notNull(),
  subject3Score: integer('subject_3_score').default(0).notNull(),
  subject4Score: integer('subject_4_score').default(0).notNull(),
  totalQuestions: integer('total_questions').default(180).notNull(),
  timeSpentSeconds: integer('time_spent_seconds').default(0).notNull(),
  subjectBreakdown: jsonb('subject_breakdown').notNull(),
  subjectScoresJson: jsonb('subject_scores_json').default({}).notNull(),
  weakTopics: jsonb('weak_topics').default([]).notNull(),
  completedAt: timestamp('completed_at', { withTimezone: true }).defaultNow().notNull(),
});

export const topicMastery = pgTable('topic_mastery', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').references(() => users.id).notNull(),
  topicId: uuid('topic_id').references(() => syllabusTopics.id).notNull(),
  subject: varchar('subject', { length: 50 }).default('UNKNOWN').notNull(),
  topicName: varchar('topic_name', { length: 255 }).default('UNKNOWN').notNull(),
  accuracyRate: real('accuracy_rate').default(0.0).notNull(),
  totalAttempts: integer('total_attempts').default(0).notNull(),
  totalAttempted: integer('total_attempted').default(0).notNull(),
  totalCorrect: integer('total_correct').default(0).notNull(),
  accuracyPercentage: decimal('accuracy_percentage', { precision: 5, scale: 2 }).default('0.00').notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export const battleStatusEnum = pgEnum('battle_status_enum', [
  'WAITING',
  'IN_PROGRESS',
  'COMPLETED',
  'CANCELLED',
]);

export const battleRooms = pgTable('battle_rooms', {
  id: uuid('id').primaryKey().defaultRandom(),
  roomCode: varchar('room_code', { length: 11 }).notNull().unique(),
  hostUserId: uuid('host_user_id').references(() => users.id).notNull(),
  opponentUserId: uuid('opponent_user_id').references(() => users.id),
  subject: subjectEnum('subject').notNull(),
  questionIds: jsonb('question_ids').notNull(),
  status: battleStatusEnum('status').default('WAITING').notNull(),
  winnerUserId: uuid('winner_user_id').references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const battleParticipants = pgTable('battle_participants', {
  id: uuid('id').primaryKey().defaultRandom(),
  roomId: uuid('room_id').references(() => battleRooms.id).notNull(),
  userId: uuid('user_id').references(() => users.id).notNull(),
  score: integer('score').default(0).notNull(),
  currentQuestionIndex: integer('current_question_index').default(0).notNull(),
  answers: jsonb('answers').default({}).notNull(),
});

export const userProgress = pgTable('user_progress', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').notNull(),
  completedModuleIds: jsonb('completed_module_ids').default([]).notNull(),
  currentStreakDays: integer('current_streak_days').default(0).notNull(),
  weakTopics: jsonb('weak_topics').default([]).notNull(),
  lastActiveDate: timestamp('last_active_date', { withTimezone: true }).defaultNow(),
});

export const institutions = pgTable('institutions', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: varchar('name', { length: 255 }).notNull(),
  type: varchar('type', { length: 50 }).notNull(),
  location: varchar('location', { length: 255 }).notNull(),
  logoUrl: text('logo_url'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const programs = pgTable('programs', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: varchar('name', { length: 255 }).notNull(),
  faculty: varchar('faculty', { length: 255 }).notNull(),
  compulsoryUtmeSubjects: jsonb('compulsory_utme_subjects').notNull(),
  requiredOlevelCredits: jsonb('required_olevel_credits').notNull(),
  averageCutOffMark: integer('average_cut_off_mark').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

// ─── 4-Step Lean MVP Tables ─────────────────────────────────────────────────

export const userAttempts = pgTable('user_attempts', {
  id: uuid('id').defaultRandom().primaryKey(),
  userId: uuid('user_id').references(() => users.id).notNull(),
  flashcardId: uuid('flashcard_id'),
  questionId: uuid('question_id'),
  selectedOption: text('selected_option'),
  isCorrect: boolean('is_correct').notNull(),
  timeSpentSeconds: integer('time_spent_seconds').notNull(),
  attemptedAt: timestamp('attempted_at', { withTimezone: true }).defaultNow().notNull(),
});

export const userAnalytics = pgTable('user_analytics', {
  id: uuid('id').defaultRandom().primaryKey(),
  userId: uuid('user_id').references(() => users.id).notNull(),
  subject: text('subject').notNull(),
  topicMasteryScore: integer('topic_mastery_score').default(0).notNull(),
  masteryScore: integer('mastery_score').default(0),
  scoreProbability: integer('score_probability').default(50).notNull(),
  strengths: jsonb('strengths').default([]),
  weaknesses: jsonb('weaknesses').default([]),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});