import { db } from '@/db';
import { pastQuestions, syllabusTopics } from '@/db/schema';
import { eq, and } from 'drizzle-orm';
import { ReviewCard } from './review-card';

export default async function ReviewExplanationsPage() {
  // Fetch all AI-generated, unreviewed explanations
  const flagged = await db
    .select({
      id:              pastQuestions.id,
      alocId:          pastQuestions.alocId,
      subject:         pastQuestions.subject,
      year:            pastQuestions.year,
      questionText:    pastQuestions.questionText,
      options:         pastQuestions.options,
      correctOption:   pastQuestions.correctOption,
      explanation:     pastQuestions.explanation,
      explanationSource: pastQuestions.explanationSource,
      topicName:       syllabusTopics.topicName,
    })
    .from(pastQuestions)
    .leftJoin(syllabusTopics, eq(pastQuestions.topicId, syllabusTopics.id))
    .where(
      and(
        eq(pastQuestions.explanationSource, 'ai_generated'),
        eq(pastQuestions.explanationReviewed, false),
      ),
    )
    .limit(50);

  return (
    <div className="min-h-screen bg-slate-950 text-white p-6">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-black tracking-tight text-white">
            🔍 Explanation Review Queue
          </h1>
          <p className="mt-2 text-slate-400 text-sm">
            These explanations were generated by AI and flagged for human review.
            Approve or edit each one before launch.
          </p>
          <div className="mt-4 flex items-center gap-3">
            <span className="rounded-full bg-amber-500/20 border border-amber-500/40 px-3 py-1 text-xs font-black text-amber-400">
              ⏳ {flagged.length} pending review
            </span>
            <span className="text-xs text-slate-500">
              Showing up to 50 at a time
            </span>
          </div>
        </div>

        {flagged.length === 0 ? (
          <div className="rounded-2xl border border-emerald-700/40 bg-emerald-900/20 p-10 text-center">
            <div className="text-4xl mb-3">✅</div>
            <p className="text-lg font-black text-emerald-400">All explanations reviewed!</p>
            <p className="text-slate-400 text-sm mt-1">
              No AI-generated explanations are pending review.
            </p>
          </div>
        ) : (
          <div className="space-y-6">
            {flagged.map((q, idx) => (
              <ReviewCard key={q.id} question={q} index={idx + 1} total={flagged.length} />
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

